services:
  # db:
  #   image: postgres:16
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./local-db:/var/lib/postgresql/data
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  web:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./household_manager:/household_manager/
      # - ./household_manager/collectstatic:/household_manager/collectstatic  # Path where Django collects static files
    environment:
      - DJANGO_SETTINGS_MODULE:household_manager.settings
    # links:
    #   - db
    # depends_on:
    #   - redis

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #     - ./household_manager/collectstatic:/household_manager/collectstatic
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web
volumes:
  static_volume: