# Generated by Django 5.0.3 on 2024-03-21 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='family',
        ),
        migrations.AddField(
            model_name='family',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.member'),
        ),
    ]
