# Generated by Django 5.0.3 on 2024-03-21 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_family_members_alter_family_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.member'),
        ),
    ]
